import {suite, test, expect} from "vitest"
import {PriorityQueueInt} from "./priority_queue_int.js"

suite("PriorityQueueInt", () => {
  test("push", () => {
    let queue = new PriorityQueueInt(10)
    queue.push(0, 1)
    queue.push(1, 10)
    queue.push(2, 4)
    queue.push(3, 8)
    queue.push(5, 11)
    expect(queue.pop()).toBe(5)
    expect(queue.pop()).toBe(1)
    expect(queue.pop()).toBe(3)
    expect(queue.pop()).toBe(2)
    expect(queue.pop()).toBe(0)
  })
  test("remove", () => {
    let queue = new PriorityQueueInt(10)
    queue.push(0, 1)
    queue.push(1, 10)
    queue.push(2, 4)
    queue.push(3, 8)
    queue.push(4, 11)
    queue.remove(1)
    queue.remove(2)
    queue.push(5, 2)
    queue.push(6, 99)
    expect(queue.pop()).toBe(6)
    expect(queue.pop()).toBe(4)
    expect(queue.pop()).toBe(3)
    expect(queue.pop()).toBe(5)
    expect(queue.pop()).toBe(0)
  })
})
