name: CI

on:
  push:
    branches: [master, next]
  pull_request:
    branches: [master, next]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - run: yarn build
      - run: yarn test --coverage

      - name: Publish code coverage report
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/clover.xml
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)

      - name: Generate typedoc
        run: yarn docs

      - name: Publish to GitHub Pages
        uses: ./
        with:
          dir: docs
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
