name: CI

on:
  issue_comment:
    types: [created]

jobs:
  createRelease:
    if: |
      github.event_name == 'issue_comment' &&
      (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER') &&
      startsWith(github.event.comment.body, '/create release')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test --coverage

      - name: Git Identity
        run: |
          git config --global user.name '3mcd'
          git config --global user.email '3mcd@users.noreply.github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump
        run: |
          yarn bump --yes

      - name: Publish code coverage report
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/clover.xml
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)

      - name: Output Version
        id: changelog
        shell: bash -ex {0}
        run: |
          version=$(node -p 'require("./lerna.json").version')
          echo "::set-output name=version::${version}"

      - name: Create release pull request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(release): v${{ steps.changelog.outputs.version }}"
          committer: GitHub <noreply@github.com>
          author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          title: "v${{ steps.changelog.outputs.version }}"
          body: |
            ## v${{ steps.changelog.outputs.version }}
            ### Breaking Changes
            - [ ] TODO
            ### Features
            - [ ] TODO
            ### Bug Fixes
            - [ ] TODO
          labels: "Type: Release"
          branch: "release/next"
          request-to-parent: false
